version: "3.7"
services:
  db:
    container_name: "mongodb"
    build: ./src/db
    restart: "always"
    ports:
      - "27017:27017"
    networks:
      - default
  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin-password
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - default
  server:
    image: node:16-slim
    container_name: "server"
    ports:
      - "8080:8080"
      - "9229:9229"
    working_dir: "/api"
    volumes:
      - ./src/api:/api
    command:
      - sh
      - -c
      - |
        npm install
        npm start
    depends_on:
      - db
    networks:
      - default
  client:
    stdin_open: true
    container_name: "client"
    build: ./src/ui
    ports:
      - "3000:3000"
    volumes:
      - "./src/ui:/app"
      - "/app/node_modules"
    command:
        - sh
        - -c
        - |
          npm install
          npm start
networks:
  default:
    external:
      name: dev-network
